### PR TITLE
Add cocktail examples from '101 Girly Drinks'

### PR DESCRIPTION
**Pull request by samayer12**
Feel free to bring this PR in if you'd like to provide ORF users many entries that use the recipe format. Might be useful for someone trying to do bulk analysis of recipe data with ORF.

### CODE REVIEW

**Comment by techhat** [comment]
What's the copyright situation on these?

**Comment by samayer12** [comment]
Looks like [Carlton Books Limited](https://www.dnb.com/business-directory/company-profiles.carlton_books_limited.3bebd959c78f6da62a80b9ff62364f38.html) holds the copyright.

> This book is sold subject to the condition that it shall not, by way of trade or otherwise, be lent, resold, hired out or otherwise circulated without the publisher's prior written consent in any form of cover or binding other than that in which it is published and without a similar condition including this condition being imposed upon the subsequent purchaser.

There's no exchange of money and I'd maintain the purpose is academic in nature.
I wonder whether crediting the source material by way of `source_book.isbn` is sufficient?

**Comment by techhat** [comment]
I would rather err on the side of safety. There's probably plenty of public domain content that could be used instead.

**Comment by samayer12** [comment]
That's reasonable. A little digging on recipes and copyright law revealed this according to the [US copyright office](https://www.copyright.gov/circs/circ33.pdf).

> A mere listing of ingredients or contents, or a simple set of directions, is uncopyrightable. A registration for a recipe may cover the written description or explanation of a process that appears in the work, as well as any photographs or illustrations that are owned by the applicant. However, the registration will not cover the list of ingredients that appear in each recipe, the underlying process for making the dish, or the resulting dish itself. The registration will also not cover the activities described in the work that are procedures, processes, or methods of operation, which are not subject to copyright protection.

At the end of the day, it's your project. Feel free to close this one!

**Pull request closed without merging**
